config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :relationships, only: [:create, :destroy]

  resources :users, only: [:show] do
    member do
      get :likesDisplay
    end
  end

  resources :posts, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get :search
    end
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @like = current_user.likes.create(post_id: params[:post_id])
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy

  end
end

app/views/likes/_like.html.haml
- if user_signed_in?
  - if post.liked_by?(current_user)
    = link_to post_like_path(post, current_user), class: "Post__icon--redlike", method: :delete, remote: true do
      = icon('fas', 'heart')
      %span<>
    .Post__icon--size
      = post.likes.size
  - else
    = link_to post_likes_path(post), class: "Post__icon--blacklike", method: :post, remote: true do
      = icon('far', 'heart')
      %span<>
    .Post__icon--size
      = post.likes.size
- else
  %p ♡

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html(
  "<%= j(render partial: 'likes/like', locals: {post: @post}) %>"
);

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html(
  "<%= j(render partial: 'likes/like', locals: {post: @post}) %>"
);