config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :relationships, only: [:create, :destroy]

  resources :users, only: [:show] do
    member do
      get :likesDisplay
    end
  end

  resources :posts, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get :search
    end
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true
  validates :profile, length: { maximum: 200 }
  validates :image, presence: true

  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_items, through: :likes, source: :post, dependent: :destroy

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  mount_uploader :image, ImageUploader

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end


end

app/controllers/users/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @user = User.find(params[:id])
    @posts = user.posts.order("created_at DESC")
    #ポスト数（投稿しているかどうか）
    if @posts.count === 0
      @count = 0
    end
  end

  def likesDisplay
    @user = User.find(params[:id])
  end
end

app/views/users/_follow_button.html.haml
- unless current_user == user
  - if current_user.following?(user)
    = form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f|
      = f.hidden_field :follow_id, value: user.id
      = f.submit 'フォロー中', class: 'follow-now'
  - else
    = form_for(current_user.relationships.build) do |f|
      = f.hidden_field :follow_id, value: user.id
      = f.submit 'フォロー', class: 'follows'

app/views/users/_posts.html.haml
.Posts
  - if @count != 0
    - @posts.each do |post|
      .Pic
        = link_to (image_tag post.image.url, class: "Pic__image"), post_path(post)
  - else
    %p.NoPost まだ投稿はありません

app/views/users/_profile.html.haml
.User
  .User__logo
    = link_to "InstaClone", root_path, class: 'User__logo--link'
  .User__image
    = image_tag @user.image.url, class: "User__image--pic"
  .User__name
    = @user.name
  .User__profile
    = @user.profile

  .User-followModal
    #followings-overlay
    #followings-modalWindow
      - if @user.followings.size == 0
        %p.title フォローしたい人を見つけましょう
      - else
        %p.title フォロー中
        - @user.followings.each do |following|
          .following__user
            = link_to (image_tag following.image.url, class: "UserInfoShow-image--searched"), user_path(following)
            = link_to following.name, user_path(following), class: "UserInfoShow-name--searched"

    #followers-overlay
    #followers-modalWindow
      - if @user.followers.size == 0
        %p.title フォロワーはまだいません。
      - else
        %p.title フォロワー
        - @user.followers.each do |follower|
          .following__user
            = link_to (image_tag follower.image.url, class: "UserInfoShow-image--searched"), user_path(follower)
            = link_to follower.name, user_path(follower), class: "UserInfoShow-name--searched"

  = render "follow_button", user: @user
  .User__numbers
    = link_to "#", class: "User__numbers--followings" do
      フォロー中
      = @user.followings.size
      人

    = link_to "#", class: "User__numbers--followers" do
      フォロワー
      = @user.followers.size
      人


  - if current_user.id == @user.id
    .User__icons
      = link_to new_post_path, class: "User__icons--post", "data-toggle" => "tooltip", "data-placement" => "bottom", :title => "新規投稿" do
        = icon('far', 'images')
        %span<>
      = link_to likesDisplay_user_path(@user), class: 'User__icons--like', "data-toggle" => "tooltip", "data-placement" => "bottom", :title => "イイネした投稿" do
        = icon('fas', 'heart')
        %span<>
      = link_to edit_user_registration_path, class: 'User__icons--cog', "data-toggle" => "tooltip", "data-placement" => "bottom", :title => "アカウント設定" do
        = icon('fas', 'cog')
  - else
    .OtherUser__icons
      = link_to likesDisplay_user_path(@user), class: 'User__icons--like', "data-toggle" => "tooltip", "data-placement" => "bottom", :title => "イイネした投稿" do
        = icon('fas', 'heart')
        %span<>

app/views/users/likesDisplay.html.haml
= render "/posts/top"
.likedPosts-wrapper
  .LikedPosts
    - if @user.likes.size != 0
      - @user.likes.each do |like|
        .LikedPic
          = link_to (image_tag like.post.image.url, class: "LikedPic__image"), post_path(like.post)
    - else
      %p.NoPost まだいいねがありません。

app/views/users/show.html.haml
.Show-wrapper
  = render "profile"
  = render "posts"